import { Toaster } from "@/components/ui/toaster";
import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Blog App | Add Blog",
    description: "Generated by create next app",
};

export default function BlogLayout({ children }: { children: React.ReactNode }) {
    return (
        <>
            <Toaster />
            {children}
        </>
    )
}