import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Providers } from "@/components/ThemeProvider";
import Navbar from "@/components/Navbar";

const inter = Poppins({ weight: ['400', '700', '900'], subsets: ['latin'] });

export const metadata: Metadata = {
  title: "Blog App | Home",
  description: "Generated by create next app",
  icons: '/vercel.svg'
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <Providers>
          <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
